language: node_js
node_js:
  - 16
sudo: false
script:
  - npm test
deploy:
  provider: heroku
  api_key:
    secure: FGVhtGLzwjwBNwZVTgFg+RUbtejW+6Z3ADcViK9TO4X7QicnxNbfHxRLZu1utMnZEgJEFtqwGO1zRMgBT7cxi2khAv5QVFSUgxS4RRmQHxsYUYpGezx6VaxVs8LTp2HPi4fWUiLTgccUACZ57XAl3DVT87yX+DmxvNXknPdRdFpBPOAZlQ4xu9Oqh35YzYh4t8TqWyQJbw7Qc+pOqnMFi2BVkFq5ZX0w9sXWR4i1Xk516dptAN757rWfw+Z3aSPLzcjFgjOcuK07vef+C4YwDMdH/OC7qHr/pPgB3yFmmVF+JYEb6cqiAqpk78yn7oV9lRc5Kp4XkQZpXKtjNJ9fghfp5BlOyNp+NkXob9PIuGuexmk4fwpn8LB9gHUsakYBisStMAhY6fDE5MS5MoD259kF6VHwqX/eLBKwXoaoqeXzsTmD4aw2wLV7Kh6uL1jnb7ZhLib91rZxN0R3dkyVv3Aynwm3TlJpu87H8kZGXvcH/haEnOvAOf3xdC3kuo24+PtqNSXX7VvVkK4s5lHNno/nV5mkhNeu7g647mxXZEmBtkAX8BjiWcvyofjhn8wqxl3R3sWLeWQSVBeTEBo/jmW9WOWOEsAX3fdJZ/rnu825jXOY23vYBjzYGgskFvB8eIuS+v8RffOM+/ma4ZKpShblWBNSKzqNVNt7cWL8LE0=
  app: devops-pipeline1
  edge: true
