language: node_js
node_js:
- 16
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: TjKwEkqYhztV0XH1H2SaaSH1ArrX0o7Jf1xBDt0/9UeO1BtjTM66LKZ5iNsmfte2qQbgKvcmVvQRQRHsNmCskaKP/eZ3bb0myZfgsJowQNpflJeAfH4fJiK3dg3jCd0fhfvV701/vSVQKIwIK197xKK+8lTXwqgVjM3p6/bP5vk8h+Vk2tETNRMuYBRYkT3tqWYktca1hfd6qqWk8IqzrIifHWP8yz9wqET9bCCbJoGuGrb3BHTx5ernjygdMW3TPOtWaRDxt8lJpxWHodE8vLmHh1PBYTKNt6yoOFw2BEClhAJ0mzPDh1Tv2CIxVyQY/ClYN25oBmsHmyy2ob94EBEtn6rmElV1PMP1B9mxrKxQYK5LuhKwcpYuyDT4SPwnxSTbIwIOkDAkjYrltZNGHLVIYpurM5/m6SWkxRAKOTYl17MK7rO9cR7e5DnEfPRWDhe+pMYE8AIqtTEz4hl1FQ3R/i6kwUjpck4H57TtpvqQvdm9CiWWZKL/ScehMA6t6oYs7wK6H7HyWpVwkjbU5hXlFiiziJyZNv1JAn89PqE86O5r0WU6QZTxyxzXXtP70YgqB0+duz0cOTQZ5gn5EZa2AKFtVJd9DLzftKSqwrHR+OMvnmCliVjSl6OfIsP62ai45QWVQtNPcodGtLj3jPalLXjse14T/In3ENkFjXI=
  app: devops-pipeline1
  edge: true
